kind: Deployment
metadata:
  name: eks-jenkins-demo
  labels:
    app: eks-jenkins-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-jenkins-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eks-jenkins-demo
    spec:
      containers:
        - image: veeranon/ecsdemo-devopt-non
          imagePullPolicy: Always
          name: eks-jenkins-demo
          ports:
            - containerPort: 8080
              protocol: TCP
